# Generated by Django 3.0.5 on 2020-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('Author', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
